### ISSUE TITLE
Possible crash?

### ISSUE THREAD

**Issue by algernon** [keyboardio/Kaleidoscope-LED-Stalker#8] opened 2017-03-27 21:17 UTC
While my wife was playing with the Stalker effect, the keyboard appeared to crash: animation became slow, and no keys registered anymore.

My suspicion is that a key with wrong (255, 255) coordinates was pressed, and the coordinates were used to address an array. And that resulted in all kinds of overflows.

Will need to reproduce reliably.

**Comment by algernon** [comment] 2017-03-27 21:25
Or, as obra suggested, it may have been `millis()` wrapping around, as the keyboard has been plugged in for a good while when this happened.

**Comment by algernon** [comment] 2017-08-16 09:46
keyboardio/Kaleidoscope#178.

**Comment by cdisselkoen** [comment] 2017-10-01 02:43
If the cause was (255,255) coordinates, this may have been fixed by keyboardio/Kaleidoscope#189.  However, I doubt that was the problem, as the core firmware was doing these out-of-bounds accesses routinely even during apparently normal operation of the keyboard.

**Comment by algernon** [comment] 2017-10-10 12:33
It might have been wrong coordinates, and unlike core, they might have caused issues here, out of sheer bad luck. I still need to reproduce this, but my gut feeling is that the root cause has been fixed since.

(Timer APIs would be neat, but that's a separate issue, and is linked above anyway.)

**Closed** 2018-04-29 06:58 UTC
Labels: bug
